spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/partnership_partnersubscription
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566
logging:
  level:
    com.company.partnership: DEBUG
